### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by peterdesmet**
Article (http://doi.org/10.1007/s10336-016-1404-9) and Zenodo package (http://doi.org/10.5281/zenodo.48423) mention this license for the source code, but the license is not added to the repository. Adding a LICENSE file is the most common method and interacts well with GitHub: license info will be shown in the header.

### CODE REVIEW

**Comment by ThierryO** [comment]
The license is mentioned the DESCRIPTION file, switch is common practice in case of R packages.

**Comment by peterdesmet** [comment]
> switch is common practice in case of R packages.

What switch? OK to have mention in description and LICENSE file?

**Comment by ThierryO** [comment]
Typo. Is should be "...which is ...". The details on the licensing of R packages is available at https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing

**Comment by peterdesmet** [comment]
Ok, but doesn't hurt to have both, especially if it is becoming a norm for software (and integrates well with GitHub)? The same is true for a README file. And Hadley does this too: https://github.com/tidyverse/ggplot2/blob/master/LICENSE 😄

**Comment by peterdesmet** [comment]
Can't wait to see it on master 😄

**Comment by ThierryO** [comment]
I'm working on a new version. Hang tight.

PS I had to update the DESCRIPTION too. It must be `License: GPL-3 | file LICENSE` instead of `License: GPL-3`

**Pull request merged**
